### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by andrew2net** [CalConnect/csd-lightweight-doc#3]
@opoudjis When I try to run `make clean all` it fails with the error:
```
FILENAME=sources/cc-36010.adoc; \
	echo "Compiling locally..."; bundle exec metanorma $FILENAME
Compiling locally...
[relaton] Info: detecting backends:
[relaton] processor "relaton_gb" registered
[relaton] processor "relaton_iec" registered
[relaton] processor "relaton_ietf" registered
[relaton] processor "relaton_iso" registered
[relaton] processor "relaton_itu" registered
[relaton] processor "relaton_nist" registered
[relaton] processor "relaton_ogc" registered
Local cache version is obsolete.
fetching ISO 639...
fetching ISO 8601-1...
fetching ISO 8601-2...
fetching ISO/IEC 10118...
fetching ISO/IEC 14888...
fetching ISO 15924...
/Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-standoc-1.3.3/lib/asciidoctor/standoc/blocks.rb:171:in `initialize': No such file or directory @ rb_sysopen - sources/basicdoc-models/images/BasicDocument.png (Errno::ENOENT)
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-standoc-1.3.3/lib/asciidoctor/standoc/blocks.rb:171:in `open'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-standoc-1.3.3/lib/asciidoctor/standoc/blocks.rb:171:in `datauri'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-standoc-1.3.3/lib/asciidoctor/standoc/blocks.rb:181:in `image_attributes'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-standoc-1.3.3/lib/asciidoctor/standoc/blocks.rb:199:in `block (2 levels) in image'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/builder.rb:394:in `insert'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/builder.rb:377:in `method_missing'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-standoc-1.3.3/lib/asciidoctor/standoc/blocks.rb:197:in `block in image'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/builder.rb:254:in `new'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/builder.rb:254:in `with'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-standoc-1.3.3/lib/asciidoctor/standoc/utils.rb:165:in `noko'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-standoc-1.3.3/lib/asciidoctor/standoc/blocks.rb:196:in `image'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-standoc-1.3.3/lib/asciidoctor/standoc/utils.rb:145:in `convert'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-standoc-1.3.3/lib/asciidoctor/standoc/section.rb:101:in `block in clause_parse'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/builder.rb:394:in `insert'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/builder.rb:377:in `method_missing'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-standoc-1.3.3/lib/asciidoctor/standoc/section.rb:99:in `clause_parse'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-standoc-1.3.3/lib/asciidoctor/standoc/section.rb:72:in `block in section'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/builder.rb:254:in `new'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/builder.rb:254:in `with'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-standoc-1.3.3/lib/asciidoctor/standoc/utils.rb:165:in `noko'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-standoc-1.3.3/lib/asciidoctor/standoc/section.rb:42:in `section'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-standoc-1.3.3/lib/asciidoctor/standoc/utils.rb:145:in `convert'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1261:in `content'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-standoc-1.3.3/lib/asciidoctor/standoc/base.rb:190:in `block in middle'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/builder.rb:394:in `insert'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/builder.rb:377:in `method_missing'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-standoc-1.3.3/lib/asciidoctor/standoc/base.rb:189:in `middle'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-csd-1.3.2/lib/asciidoctor/csd/converter.rb:29:in `block in makexml'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/builder.rb:254:in `new'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/builder.rb:254:in `with'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-standoc-1.3.3/lib/asciidoctor/standoc/utils.rb:165:in `noko'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-csd-1.3.2/lib/asciidoctor/csd/converter.rb:29:in `makexml'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-csd-1.3.2/lib/asciidoctor/csd/converter.rb:40:in `document'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-standoc-1.3.3/lib/asciidoctor/standoc/utils.rb:145:in `convert'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1190:in `convert'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1521:in `convert'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-0.3.15/lib/metanorma/input/asciidoc.rb:8:in `process'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-csd-1.3.2/lib/metanorma/csd/processor.rb:26:in `input_to_isodoc'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-0.3.15/lib/metanorma/compile.rb:101:in `process_input'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-0.3.15/lib/metanorma/compile.rb:17:in `compile'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-cli-1.2.7/lib/metanorma/cli/compiler.rb:41:in `compile_file'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-cli-1.2.7/lib/metanorma/cli/compiler.rb:29:in `compile'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-cli-1.2.7/lib/metanorma/cli/compiler.rb:33:in `compile'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-cli-1.2.7/lib/metanorma/cli/command.rb:34:in `compile'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-cli-1.2.7/lib/metanorma/cli.rb:60:in `start'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/metanorma-cli-1.2.7/exe/metanorma:20:in `<top (required)>'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/bin/metanorma:23:in `load'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/bin/metanorma:23:in `<main>'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/andrej/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
make: *** [sources/cc-36010.xml] Error 1
```

**Comment by opoudjis** [comment]
Oh, that damn thing. You're going to have to do `git submodule update`, and possibly `git submodule init` before you do that. The images come from metanorma/basicdoc-models.
